// Test-only self-signed certificate. It is not trusted and is never used by runtime code.
export const TEST_TLS_KEY = `-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgzaUJ/i0Sf/n/X5A+
hLGe2pmprrQqnzoHmGkfE0Zn1uShRANCAARl8tquMIVXQpdYngTzzuohTXd33ij+
QRnlRBslH14K0ae5RtknxKeiPV5x/tm4jYS9sSHzPtJACZ1+MKDX+Jzi
-----END PRIVATE KEY-----`;

export const TEST_TLS_CERT = `-----BEGIN CERTIFICATE-----
MIIBqDCCAU+gAwIBAgIUDimX5i6Cdd+PeExtoF8o34DL0jowCgYIKoZIzj0EAwIw
HDEaMBgGA1UEAwwRQ2luZVZGWCBURVNUIE9OTFkwHhcNMjYwODExMjIxMTU5WhcN
MzYwODA4MjIxMTU5WjAcMRowGAYDVQQDDBFDaW5lVkZYIFRFU1QgT05MWTBZMBMG
ByqGSM49AgEGCCqGSM49AwEHA0IABGXy2q4whVdCl1ieBPPO6iFNd3feKP5BGeVE
GyUfXgrRp7lG2SfEp6I9XnH+2biNhL2xIfM+0kAJnX4woNf4nOKjbzBtMB0GA1Ud
DgQWBBS9dNxIvZ6Dg0FVKUlw7TmByZ9zsjAfBgNVHSMEGDAWgBS9dNxIvZ6Dg0FV
KUlw7TmByZ9zsjAPBgNVHRMBAf8EBTADAQH/MBoGA1UdEQQTMBGHBH8AAAGCCWxv
Y2FsaG9zdDAKBggqhkjOPQQDAgNHADBEAiBrIZkgFBSWwQXwvtWQgrvydFJCQuuL
matEu1sbYnZH6wIgQiqFRPGIJgva0Q0kuY5EndvhACSW3ZSo+xCe7Dlyh9A=
-----END CERTIFICATE-----`;
